"""Shared OCR extraction prompt — all providers use this so results are comparable."""

EXTRACTION_PROMPT = (
    "당신은 한국 자동차등록증 OCR 추출기다. 첨부 이미지/본문에서 아래 9개 키만 가진 JSON 객체 "
    "하나만 출력하라. 코드펜스·설명·다른 텍스트 금지. 값을 못 읽으면 null.\n"
    "\n"
    "키:\n"
    "- owner_name: 소유자의 성명/법인명만. 주소는 절대 포함하지 마라.\n"
    "    · 개인이면 사람 이름 (예: '홍길동').\n"
    "    · 법인이면 회사 이름 (예: '(주)카비드', '(주)카비드 이천지점').\n"
    "    · 등록증의 '소유자' 행이 한 줄에 [주소][회사명] 으로 같이 적혀 있어도, 행정구역·도로명·번지를 "
    "      빼고 회사명만 owner_name 으로 출력하라.\n"
    "- owner_ssn: 주민(법인)등록번호. 형식 예: '860101-1234567' 또는 법인등록번호.\n"
    "- owner_address: 소유자 주소(또는 사용본거지). 도/시/구/읍/면/동/번지/도로명·번길 이 포함된 한 줄. "
    "      회사명은 owner_address 에 넣지 마라. 개행은 공백으로, 중복 공백은 1개로.\n"
    "- vehicle_reg_no: 자동차등록번호 (예: '123가4567').\n"
    "- vehicle_vin: 차대번호. 공백 없는 영문 대문자+숫자.\n"
    "- vehicle_model: 차명.\n"
    "- vehicle_year: 형식·연식 — 가능하면 4자리 연도.\n"
    "- vehicle_mileage: 주행거리(km) 정수 또는 null. 콤마·단위 빼고.\n"
    "- vehicle_weight: 차량총중량(kg) 정수. 없으면 차량중량, 둘 다 없으면 null.\n"
    "\n"
    "위 9개 외의 키는 만들지 마라. 모든 숫자는 콤마·단위 없이 정수만."
)
